---
-  name: Install Packages
   apt: name={{ item }} update_cache=yes state=latest
   with_items:
     build-essential
     npm
     nodejs-legacy
     git
     openjdk-8-jdk
     maven
     yarn
     elasticsearch