---
#
#Updating Repo in Remote server
#
- name: Update APT package manager repositories cache
  apt:
    update_cache: yes

- name: Install OpenJDK Java
  become: yes
  apt:
    name: java
    state: present
  with_items:
    openjdk-8-jdk
