---
#
#Updating Repo in Remote server
#
- name: Update APT package manager repositories cache
  apt:
    update_cache: yes
# Installing Java package
- name: Install OpenJDK Java
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    openjdk-8-jdk
# Installing Maven package
- name: Install Maven
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    maven
# Installing Yarn package
- name: Install Yarn 
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    yarn
# Installing Node package

- name: Install Node Js
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    nodejs

